In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
data = pd.read_csv('Final_Dataset_2023.csv')
data.tail(15)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,Predictions
99985,80,0,688,1,26,0,181629,10.6,128,1,1,1
99986,55,0,248,1,38,0,195200,10.6,136,0,0,0
99987,85,0,598,0,41,0,269076,10.6,101,1,0,1
99988,80,0,24,1,36,1,111615,10.7,134,1,1,1
99989,66,0,48,1,40,1,219892,10.9,136,0,0,0
99990,65,1,590,0,28,0,203542,11.0,127,1,1,1
99991,82,1,94,1,26,0,106300,11.1,135,0,0,1
99992,65,0,501,1,35,0,162233,11.3,133,1,0,1
99993,64,1,48,1,38,0,86935,11.4,125,1,0,0
99994,80,0,92,0,41,0,34958,11.5,137,1,1,0
99995,80,1,450,0,20,0,180590,11.5,131,0,0,1
99996,81,0,362,0,39,0,235391,11.7,135,1,1,1
99997,80,0,654,1,34,0,169462,11.7,135,1,1,1
99998,85,0,5704,0,41,0,297746,12.0,124,1,0,1
99999,80,1,739,0,34,0,193621,12.0,129,1,1,1

In [3]:
# Separate features and target variable
X = data.drop('Predictions', axis=1)
y = data['Predictions']
X.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking
0,70,1,402,0,36,1,216359,1.8,133,1,1
1,90,1,124,1,38,0,187570,1.4,139,1,1
2,50,0,39,0,39,0,245416,1.0,126,1,1
3,75,0,21,0,39,1,280768,0.9,134,1,1
4,85,1,96,0,38,0,198585,0.7,139,1,1

In [4]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
# Build the DNN model
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [7]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
# Train the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
2000/2000 [==============================] - 8s 3ms/step - loss: 0.5420 - accuracy: 0.7309 - val_loss: 0.5378 - val_accuracy: 0.7333
Epoch 2/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5289 - accuracy: 0.7411 - val_loss: 0.5357 - val_accuracy: 0.7339
Epoch 3/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5258 - accuracy: 0.7435 - val_loss: 0.5324 - val_accuracy: 0.7384
Epoch 4/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5234 - accuracy: 0.7441 - val_loss: 0.5313 - val_accuracy: 0.7401
Epoch 5/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5218 - accuracy: 0.7446 - val_loss: 0.5312 - val_accuracy: 0.7418
Epoch 6/50
2000/2000 [==============================] - 8s 4ms/step - loss: 0.5198 - accuracy: 0.7466 - val_loss: 0.5313 - val_accuracy: 0.7399
Epoch 7/50
2000/2000 [==============================] - 7s 4ms/step - loss: 0.5184 - accuracy: 0.7475 - val_loss: 0.5296 - val_accuracy: 0.7403
Epoch 8/50
2000/2000 [==============================] - 7s 4ms/step - loss: 0.5175 - accuracy: 0.7472 - val_loss: 0.5280 - val_accuracy: 0.7411
Epoch 9/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5160 - accuracy: 0.7501 - val_loss: 0.5264 - val_accuracy: 0.7419
Epoch 10/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5154 - accuracy: 0.7487 - val_loss: 0.5284 - val_accuracy: 0.7401
Epoch 11/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5140 - accuracy: 0.7498 - val_loss: 0.5271 - val_accuracy: 0.7394
Epoch 12/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5129 - accuracy: 0.7511 - val_loss: 0.5284 - val_accuracy: 0.7396
Epoch 13/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5122 - accuracy: 0.7510 - val_loss: 0.5259 - val_accuracy: 0.7423
Epoch 14/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5111 - accuracy: 0.7510 - val_loss: 0.5274 - val_accuracy: 0.7429
Epoch 15/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5103 - accuracy: 0.7532 - val_loss: 0.5275 - val_accuracy: 0.7426
Epoch 16/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5094 - accuracy: 0.7527 - val_loss: 0.5262 - val_accuracy: 0.7449
Epoch 17/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5088 - accuracy: 0.7535 - val_loss: 0.5273 - val_accuracy: 0.7416
Epoch 18/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5087 - accuracy: 0.7535 - val_loss: 0.5265 - val_accuracy: 0.7431
Epoch 19/50
2000/2000 [==============================] - 8s 4ms/step - loss: 0.5075 - accuracy: 0.7536 - val_loss: 0.5262 - val_accuracy: 0.7427
Epoch 20/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5071 - accuracy: 0.7532 - val_loss: 0.5268 - val_accuracy: 0.7422
Epoch 21/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5066 - accuracy: 0.7554 - val_loss: 0.5274 - val_accuracy: 0.7421
Epoch 22/50
2000/2000 [==============================] - 7s 4ms/step - loss: 0.5057 - accuracy: 0.7551 - val_loss: 0.5254 - val_accuracy: 0.7435
Epoch 23/50
2000/2000 [==============================] - 8s 4ms/step - loss: 0.5054 - accuracy: 0.7553 - val_loss: 0.5267 - val_accuracy: 0.7427
Epoch 24/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5050 - accuracy: 0.7567 - val_loss: 0.5282 - val_accuracy: 0.7422
Epoch 25/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5046 - accuracy: 0.7562 - val_loss: 0.5274 - val_accuracy: 0.7417
Epoch 26/50
2000/2000 [==============================] - 7s 4ms/step - loss: 0.5046 - accuracy: 0.7563 - val_loss: 0.5266 - val_accuracy: 0.7404
Epoch 27/50
2000/2000 [==============================] - 8s 4ms/step - loss: 0.5038 - accuracy: 0.7557 - val_loss: 0.5288 - val_accuracy: 0.7421
Epoch 28/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5037 - accuracy: 0.7568 - val_loss: 0.5278 - val_accuracy: 0.7399
Epoch 29/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5030 - accuracy: 0.7563 - val_loss: 0.5283 - val_accuracy: 0.7402
Epoch 30/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5028 - accuracy: 0.7559 - val_loss: 0.5288 - val_accuracy: 0.7426
Epoch 31/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5021 - accuracy: 0.7570 - val_loss: 0.5275 - val_accuracy: 0.7418
Epoch 32/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5020 - accuracy: 0.7571 - val_loss: 0.5296 - val_accuracy: 0.7414
Epoch 33/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5014 - accuracy: 0.7572 - val_loss: 0.5309 - val_accuracy: 0.7404
Epoch 34/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5011 - accuracy: 0.7580 - val_loss: 0.5295 - val_accuracy: 0.7421
Epoch 35/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5012 - accuracy: 0.7568 - val_loss: 0.5281 - val_accuracy: 0.7427
Epoch 36/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.5006 - accuracy: 0.7591 - val_loss: 0.5303 - val_accuracy: 0.7393
Epoch 37/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5010 - accuracy: 0.7577 - val_loss: 0.5314 - val_accuracy: 0.7393
Epoch 38/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.5000 - accuracy: 0.7588 - val_loss: 0.5305 - val_accuracy: 0.7382
Epoch 39/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4996 - accuracy: 0.7577 - val_loss: 0.5303 - val_accuracy: 0.7408
Epoch 40/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4995 - accuracy: 0.7599 - val_loss: 0.5305 - val_accuracy: 0.7385
Epoch 41/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4992 - accuracy: 0.7585 - val_loss: 0.5321 - val_accuracy: 0.7387
Epoch 42/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4991 - accuracy: 0.7601 - val_loss: 0.5313 - val_accuracy: 0.7424
Epoch 43/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.4984 - accuracy: 0.7593 - val_loss: 0.5301 - val_accuracy: 0.7402
Epoch 44/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4983 - accuracy: 0.7599 - val_loss: 0.5293 - val_accuracy: 0.7421
Epoch 45/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.4981 - accuracy: 0.7589 - val_loss: 0.5302 - val_accuracy: 0.7399
Epoch 46/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4982 - accuracy: 0.7597 - val_loss: 0.5313 - val_accuracy: 0.7423
Epoch 47/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4977 - accuracy: 0.7595 - val_loss: 0.5277 - val_accuracy: 0.7410
Epoch 48/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4975 - accuracy: 0.7608 - val_loss: 0.5302 - val_accuracy: 0.7408
Epoch 49/50
2000/2000 [==============================] - 6s 3ms/step - loss: 0.4972 - accuracy: 0.7600 - val_loss: 0.5286 - val_accuracy: 0.7417
Epoch 50/50
2000/2000 [==============================] - 7s 3ms/step - loss: 0.4971 - accuracy: 0.7608 - val_loss: 0.5311 - val_accuracy: 0.7431

In [9]:
# Evaluate the model on the test set
y_pred_prob = model.predict(X_test_scaled)
y_pred = np.round(y_pred_prob)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

625/625 [==============================] - 1s 2ms/step
Accuracy: 0.74735

In [10]:
#Prediction
# Assuming we have a new data point for which you want to make a prediction
new_data = np.array([[70,1,402,0,36,1,216359,1.8,133,1,1]])
new_data1 = np.array([[85,1,96,0,38,0,198585,0.7,139,1,1]])
new_data2 = np.array([[57,1,121,0,32,0,292119,2.3,147,0,0]])

In [11]:
# Standardize the new data using the same scaler
new_data_scaled = scaler.transform(new_data1)
new_data_scaled

C:\Users\sanhi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[ 1.95801677,  0.93712262, -0.56243462, -0.91509065, -0.05591325,
        -0.67673115, -0.70106664, -0.80176006,  0.82667527,  0.71105481,
         1.49387763]])

In [12]:
# Make predictions
prediction = (model.predict(new_data_scaled)>0.5).astype(int).flatten()

1/1 [==============================] - 0s 96ms/step

In [13]:
# Print the prediction
prediction= prediction.astype(bool)
print(f'The predicted class is: {prediction}')

The predicted class is: [False]

In [14]:
import pickle

In [15]:
pickle.dump(model,open('dnn.pkl','wb'))